apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ru">
      <head>
        <meta charset="UTF-8"
        <title>Создать приложение с вашей веб-страницей, доступной по HTTPS</title>
      </head>
      <body>
        <h1>HTTPS работает!</h1>
      </body>
    </html>
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;

        server_name  localhost;
        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
